[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "napariTFM"
version = "1.0"
description = "A napari plugin for Traction Force Microscopy analysis"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Artur Ruppel", email = "artur@ruppel.pro"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: napari",
]
dependencies = [
    "napari[pyqt]>=0.7.0",
    "solidspy>=1.1.0",
    "scipy>=1.9.3",
    "scikit-image>=0.24.0",
    "numpy>=1.25.2",
    "opencv-python>=4.8.0",
    "tifffile>=2024.6.18",
    "pyyaml>=6.0.2",
    "gmsh>=4.13.1",
    "numba>=0.60.0",
    "imageio>=2.36.1",
    "matplotlib>=3.9.4",
    "qtpy>=2.4.1",
    "qtrangeslider>=0.1.5",
    "vispy>=0.14.3",
    "pandas>=2.2.3",
    "pyarrow>=14.0.0",
    "tqdm>=4.66.5",
]

[project.entry-points."napari.manifest"]
napariTFM = "napariTFM:napari.yaml"

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["_dev", "_validation", "_documentation", "docs"]

[tool.setuptools]
packages = {find = {exclude = ["_dev*", "_validation*"]}}

[tool.setuptools.package-data]
"napariTFM" = ["*.py", "*.yaml"]

[tool.pylint.messages_control]
disable = [
    "import-error",
    "no-name-in-module", 
    "import-outside-toplevel",
    "broad-except",
    "trailing-whitespace",
    "missing-function-docstring"
]
