# List of folders to analyze
root_folders:
  - "C:/Users/aruppel/Desktop/test"


analysis_steps:
  create_masks: false
  displacement: false
  force: false
  preprocessing: false
  stress: false
input_files:
  beads: beads.tif
  cells: cells.tif
  reference: reference.tif
parameters:
  cell_gaussian_sigma: 80.0
  cell_max_intensity: 99.9
  cell_min_intensity: 75.0
  d_max: 0.4
  density_factor: 0.025
  dilation: 10
  disp_arrow_scale: 1.0
  disp_vector_stride: 20
  downscale_factor: 4
  epsilon: 0.01
  f_max: 200
  force_arrow_scale: 1.0
  force_vector_stride: 20
  frame_interval: 2.0
  gaussian_sigma: 0.0
  gel_height: null
  inner_iterations: 15
  lambda_: 0.4
  lanczos_exp: 5
  max_intensity: 99.9
  max_stress: 1.0
  median_filtering: 5
  mesh_algorithm: Frontal-Del.
  min_intensity: 80.0
  nscales: 3
  outer_iterations: 5
  pixel_size: 0.1
  poisson_ratio_cells: 0.5
  poisson_ratio_substrate: 0.5
  registration_mode: translation
  regularization: 0.00015848931924611142
  scale_step: 0.5
  smoothing_sigma: 40.0
  tau: 0.25
  theta: 0.3
  threshold: 29.0
  use_optimization: true
  warps: 3
  young_modulus: 6000.0
visualizations:
  bead_overlay: true
  displacement_map: true
  force_cell_overlay: true
  force_map: true
  mesh: true
  normal_stress: true
  sigma_xx: true
  sigma_yy: true
