# Configuration for generating dipole benchmark fields
[dataset]
name = "dipole_benchmark"

[substrate]
E = 20000.0  # Pa - Young's modulus
nu = 0.5    # Poisson's ratio

[image]
spacing_xy = 0.1  # µm
spacing_z = 1  # µm

[simulation]
n_points_xy = 700
n_points_z = 1

[adheasion.dipole_1]
type = "dipole"
F = 0.02   # µN - Total tangential force per adhesion site (1e-9 N)
Fz = 0.0    # µN - Normal force
F_unit = "µN"
d = 50.0     # µm - Distance between counteracting adhesion sites
phi = 45    # degrees - angle
a = 3     # µm - Radius of adhesion site (extent/2)
pos = [0, 0] # µm - Position of dipole center

[adheasion.dipole_2]
type = "dipole"
F = 0.02    # µN - Total tangential force per adhesion site (1e-9 N)
Fz = 0.0    # µN - Normal force
F_unit = "µN"
d = 50.0     # µm - Distance between counteracting adhesion sites
phi = -45   # degrees - angle
a = 3     # µm - Radius of adhesion site (extent/2)
pos = [0, 0] # µm - Position of dipole center
